6element:
  build: .
  command: bash -c "npm run dev"
  links:
   - "db:postgres"
  ports:
   - "4000:4000"
  environment:
   - VIRTUAL_HOST=6element.ants.builders 
   - VIRTUAL_PORT=4000
   - DEBUG=true
   - POSTGRES_CONSTRING="postgres://postgres:elements@db:5432/postgres"
  volumes:
   - app:/6element/app
db:
   image: postgres:9.4
   environment:
      - POSTGRES_USER=elements
      - POSTGRES_PASSWORD=elements
   ports:
      - "5432:5432"
   volumes:
      - /data/6element/db:/var/lib/postgresql/data
