app:
  build: .
  command: npm run start-app-dev
  links:
   - "db:postgres"
  ports:
   - "4000:4000"
  environment:
   - VIRTUAL_HOST=6element.ants.builders 
   - VIRTUAL_PORT=4000
   - DEBUG=true
   - NODE_ENV=development
  volumes:
   - app:/6element/app
admin:
  build: .
  command: npm run start-admin-dev
  links:
   - "db:postgres"
  ports:
   - "4001:4001"
  environment:
   - VIRTUAL_HOST=admin.6element.ants.builders 
   - VIRTUAL_PORT=4001
   - DEBUG=true
   - NODE_ENV=development
  volumes:
   - app:/6element/app
db:
  image: postgres:9.4
  environment:
   - POSTGRES_PASSWORD=password
  ports:
   - "5432:5432"