6element:
   build: .
   command: bash -c "npm run prod"
   links:
      - db
   ports:
      - "4000:4000"
   environment:
      - VIRTUAL_HOST=6element.ants.builders 
      - VIRTUAL_PORT=4000
      - POSTGRES_CONSTRING="postgres://postgres:elements@db:5432/postgres"
   volumes:
      - app:/6element/app
   restart: always

db:
   image: postgres:9.4
   environment:
      - POSTGRES_PASSWORD=elements
   volumes:
      - /data/6element/db:/var/lib/postgresql/data
   restart: always
