6element:
  build: .
  command: nodemon server/index.js
  links:
   - "db:postgres"
  ports:
   - "4000:4000"
  environment:
   - VIRTUAL_HOST=6element.ants.builders 
   - VIRTUAL_PORT=4000
  volumes:
   - .:/6element
db:
  image: postgres:9.4
  environment:
   - POSTGRES_PASSWORD=password
  ports:
   - "5432:5432"