6element:
  build: .
  command: forever server/index.js
  volumes:
    - ".:/6element"
  links:
   - "db:postgres"
  ports:
   - "4000:4000"
  environment:
   - VIRTUAL_HOST=6element.ants.builders 
   - VIRTUAL_PORT=4000
db:
  image: postgres:9.4
  environment:
   - POSTGRES_PASSWORD=password